########################################################################
# File::    20110223110532_add_audits_table.rb
# (C)::     https://github.com/collectiveidea/acts_as_audited/tree/1.1-stable
#
# Purpose:: Auto-generated by the Acts As Audited gem. Stores audit
#           information for models which declare themselves as audited.
# ----------------------------------------------------------------------
#           23-Feb-2011 (ADH): Created.
########################################################################

class AddAuditsTable < ActiveRecord::Migration
  def self.up
    create_table :audits, :force => true do |t|
      t.column :auditable_id, :integer
      t.column :auditable_type, :string
      t.column :user_id, :integer
      t.column :user_type, :string
      t.column :username, :string
      t.column :action, :string
      t.column :changes, :text
      t.column :version, :integer, :default => 0
      t.column :created_at, :datetime
    end
    
    add_index :audits, [:auditable_id, :auditable_type], :name => 'auditable_index'
    add_index :audits, [:user_id, :user_type], :name => 'user_index'
    add_index :audits, :created_at  
  end

  def self.down
    drop_table :audits
  end
end
